# TOML format configuration file for the `PhageGap Classifer` software.

title = "PhageGap Classifer 1.0.0-alpha Configuration"

[app]
max_content_length = 500_000
max_form_memory_size = 500_000
max_form_parts = 1000
host = "0.0.0.0"
port = 5001
debug = false
api_token_path = "secrets/phagegap_api_token"

[setup]
seed = 42
device = "cpu"

[embed]
model_type = "prot_t5"
pool_layers = [ ]
pool_strategy = "mean"

[predict]
model_path = "models/cnn_model1_final.pt"
model_type = "cnn"

[manifold]
pca_path = "models/pca.joblib"
tsne_path = "models/tsne.joblib"
