# TOML format configuration file for the `PhageGAP` classifier software.

title = "PhageGAP Classifer 1.0.0 Configuration"

[app]
max_content_length = 500_000
max_form_memory_size = 500_000
max_form_parts = 1000
api_token_path = "secrets/phagegap_api_token"
structure_info_path = "phagegap_structures.tsv"

[setup]
seed = 42
device = "cuda"

[embed]
model_type = "prot_t5"
pool_layers = [ ]
pool_strategy = "mean"

[predict]
model_path = "models/cnn_model1_final.pt"
model_type = "cnn"

[manifold]
pca_path = "models/pca.joblib"
tsne_path = "models/tsne.joblib"
