# TOML format configuration file for the `PhageGAP` classifier software.

title = "PhageGAP Classifer 1.0.0 Configuration"

[app]
max_content_length = 500_000
max_form_memory_size = 500_000
max_form_parts = 1000
api_token_path = "secrets/phagegap-api-token"

[setup]
seed = 42
device = "cuda"

[embed]
model_type = "prot_t5"
pool_layers = [ ]
pool_strategy = "mean"

[predict]
model_path = "models/phagegap-cnn.pt"
model_type = "cnn"

[manifold]
pca_path = "models/phagegap-pca.joblib"
tsne_path = "models/phagegap-tsne.joblib"
